apiVersion: v1
kind: Service
metadata:
  name: employee-service
spec:
  type: NodePort
  selector:
    app: employee
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8888
      nodePort: 31000
